![](numpy_array_t.png)

### Тема “Вычисления с помощью Numpy”

**Задание 1**  

Импортируйте библиотеку Numpy и дайте ей псевдоним np.
Создайте массив Numpy под названием a размером 5x2, то есть состоящий из 5 строк и 2 столбцов. Первый столбец должен содержать числа 1, 2, 3, 3, 1, а второй - числа 6, 8, 11, 10, 7. Будем считать, что каждый столбец - это признак, а строка - наблюдение. Затем найдите среднее значение по каждому признаку, используя метод mean массива Numpy. Результат запишите в массив mean_a, в нем должно быть 2 элемента.


In [1]:
import numpy as np

In [2]:
np.array(10).ndim

0

In [3]:
a = np.array([[1, 2, 3, 3, 1],
             [6, 8, 11, 10, 7]]).T
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [5]:
a.ndim

2

In [44]:
mean_a = a.mean(axis=1)
mean_a

array([3.5, 5. , 7. , 6.5, 4. ])

**Задание 2**

Вычислите массив a_centered, отняв от значений массива “а” средние значения соответствующих признаков, содержащиеся в массиве mean_a. Вычисление должно производиться в одно действие. Получившийся массив должен иметь размер 5x2.


In [7]:
a_centered = a - mean_a
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

**Задание 3**  
Найдите скалярное произведение столбцов массива a_centered. В результате должна получиться величина a_centered_sp. Затем поделите a_centered_sp на N-1, где N - число наблюдений.


In [ ]:
N x M

In [47]:
a_centered[:, 0].shape

(5,)

In [8]:
a_centered_sp = np.dot(a_centered[:, 0], a_centered[:, 1]) / (a_centered.shape[0] - 1)
a_centered_sp

2.0

In [9]:
a_centered[:, 0].dot(a_centered[:, 1]), a_centered[:, 0] @ a_centered[:, 1]

(8.0, 8.0)

**Задание 4**  
Число, которое мы получили в конце задания 3 является ковариацией двух признаков, содержащихся в массиве “а”. В задании 4 мы делили сумму произведений центрированных признаков на N-1, а не на N, поэтому полученная нами величина является несмещенной оценкой ковариации.


В этом задании проверьте получившееся число, вычислив ковариацию еще одним способом - с помощью функции np.cov. В качестве аргумента m функция np.cov должна принимать транспонированный массив “a”. В получившейся ковариационной матрице (массив Numpy размером 2x2) искомое значение ковариации будет равно элементу в строке с индексом 0 и столбце с индексом 1.


In [10]:
np.cov(a.T)

array([[1. , 2. ],
       [2. , 4.3]])

In [11]:
np.cov(a.T)[0,1]

2.0

### Тема “Работа с данными в Pandas”

**Задание 1**  
Импортируйте библиотеку Pandas и дайте ей псевдоним pd. Создайте датафрейм authors со столбцами author_id и author_name, в которых соответственно содержатся данные: [1, 2, 3] и ['Тургенев', 'Чехов', 'Островский'].
Затем создайте датафрейм book cо столбцами author_id, book_title и price, в которых соответственно содержатся данные: 
[1, 1, 1, 2, 2, 3, 3], 
['Отцы и дети', 'Рудин', 'Дворянское гнездо', 'Толстый и тонкий', 'Дама с собачкой', 'Гроза', 'Таланты и поклонники'],
[450, 300, 350, 500, 450, 370, 290].


In [12]:
import pandas as pd

In [33]:
authors = pd.DataFrame({'author_id':[1, 2, 3],
                      'author_name':['Тургенев', 'Чехов', 'Островский']})
books = pd.DataFrame({'author_id':[1, 1, 1, 2, 2, 3, 3],
                   'book_title':['Отцы и дети', 'Рудин', 'Дворянское гнездо', 'Толстый и тонкий', 'Дама с собачкой', 'Гроза', 'Таланты и поклонники'],
                   'price':[450, 300, 350, 500, 450, 370, 290]})
authors

author_id author_name
0          1    Тургенев
1          2       Чехов
2          3  Островский

**Задание 2**  
Получите датафрейм authors_price, соединив датафреймы authors и books по полю author_id.


In [38]:
authors_price = pd.merge(left=authors, right=books, how='inner', on='author_id')
authors_price

author_id author_name            book_title  price
0          1    Тургенев           Отцы и дети    450
1          1    Тургенев                 Рудин    300
2          1    Тургенев     Дворянское гнездо    350
3          2       Чехов      Толстый и тонкий    500
4          2       Чехов       Дама с собачкой    450
5          3  Островский                 Гроза    370
6          3  Островский  Таланты и поклонники    290

**Задание 3**  
Создайте датафрейм top5, в котором содержатся строки из authors_price с пятью самыми дорогими книгами.


In [15]:
top5 = authors_price.sort_values('price', ascending=False).head(5)
top5

author_id author_name         book_title  price
3          2       Чехов   Толстый и тонкий    500
0          1    Тургенев        Отцы и дети    450
4          2       Чехов    Дама с собачкой    450
5          3  Островский              Гроза    370
2          1    Тургенев  Дворянское гнездо    350

In [16]:
authors_price.nlargest(5, 'price')

author_id author_name         book_title  price
3          2       Чехов   Толстый и тонкий    500
0          1    Тургенев        Отцы и дети    450
4          2       Чехов    Дама с собачкой    450
5          3  Островский              Гроза    370
2          1    Тургенев  Дворянское гнездо    350

In [17]:
authors_price.sort_values(by=['price'], ascending=False).head(5).reset_index(drop=True)

author_id author_name         book_title  price
0          2       Чехов   Толстый и тонкий    500
1          1    Тургенев        Отцы и дети    450
2          2       Чехов    Дама с собачкой    450
3          3  Островский              Гроза    370
4          1    Тургенев  Дворянское гнездо    350

**Задание 4**  
Создайте датафрейм authors_stat на основе информации из authors_price. В датафрейме authors_stat должны быть четыре столбца:
author_name, min_price, max_price и mean_price,
в которых должны содержаться соответственно имя автора,минимальная, максимальная и средняя цена на книги этого автора.


In [48]:
# 1 вариант
authors_stat = authors_price.groupby('author_name')['price'].agg(['min', 'max', 'mean'])
authors_stat.rename(columns={'max': 'max_price', 
                             'mean': 'mean_price', 
                             'min': 'min_price'}, 
                    inplace=True)
authors_stat.reset_index(level='author_name', inplace=True)
authors_stat

author_name  min_price  max_price  mean_price
0  Островский        290        370  330.000000
1    Тургенев        300        450  366.666667
2       Чехов        450        500  475.000000

In [19]:
# 2 вариант
authors_stat = authors_price.groupby('author_name').agg(
    min_price=pd.NamedAgg(column='price', aggfunc='min'),
    max_price=pd.NamedAgg(column='price', aggfunc='max'),
    mean_price=pd.NamedAgg(column='price', aggfunc='mean'))
authors_stat.reset_index(level='author_name', inplace=True)
authors_stat

author_name  min_price  max_price  mean_price
0  Островский        290        370  330.000000
1    Тургенев        300        450  366.666667
2       Чехов        450        500  475.000000

In [20]:
# 3 вариант
authors_stat = authors_price.groupby('author_name').agg(
    min_price=('price', 'min'),
    max_price=('price', 'max'),
    mean_price=('price', 'mean'))
authors_stat.reset_index(level='author_name', inplace=True)
authors_stat

author_name  min_price  max_price  mean_price
0  Островский        290        370  330.000000
1    Тургенев        300        450  366.666667
2       Чехов        450        500  475.000000

In [21]:
# 4 вариант
authors_stat = authors_price.groupby('author_name')['price'].agg(
    min_price='min',
    max_price='max',
    mean_price='mean')
authors_stat.reset_index(level='author_name', inplace=True)
authors_stat

author_name  min_price  max_price  mean_price
0  Островский        290        370  330.000000
1    Тургенев        300        450  366.666667
2       Чехов        450        500  475.000000

In [22]:
# 5 вариант
autor_name = authors_price['author_name'].unique()
min_price = authors_price.groupby('author_id')['price'].min()
mean_price = authors_price.groupby('author_id')['price'].mean()
max_price = authors_price.groupby('author_id')['price'].max()

authors_stat = pd.DataFrame({'author_name' : autor_name,
                              'min_price' : min_price,
                              'mean_price' : mean_price,
                              'max_price' : max_price})
authors_stat.reset_index(drop=True, inplace=True)
authors_stat

author_name  min_price  mean_price  max_price
0    Тургенев        300  366.666667        450
1       Чехов        450  475.000000        500
2  Островский        290  330.000000        370

In [23]:
# 6 вариант
authors_stat = pd.pivot_table(data=authors_price, 
                              index=['author_name'], 
                              values=['price'],
                              aggfunc={'price':[min, max, np.mean]}).rename(
    columns={"max":"max_price",
             "min":"min_price",
             "mean":"mean_price"})

authors_stat.columns = authors_stat.columns.droplevel(0)         
authors_stat = authors_stat.reset_index(level='author_name') 
authors_stat

author_name  max_price  mean_price  min_price
0  Островский      370.0  330.000000      290.0
1    Тургенев      450.0  366.666667      300.0
2       Чехов      500.0  475.000000      450.0

In [49]:
print(authors_stat.to_string(index = False))

author_name  min_price  max_price  mean_price
 Островский        290        370  330.000000
   Тургенев        300        450  366.666667
      Чехов        450        500  475.000000


**Задание 5 (*)**  
Создайте новый столбец в датафрейме authors_price под названием cover, в нем будут располагаться данные о том, какая обложка у данной книги - твердая или мягкая. В этот столбец поместите данные из следующего списка:
['твердая', 'мягкая', 'мягкая', 'твердая', 'твердая', 'мягкая', 'мягкая'].
Просмотрите документацию по функции pd.pivot_table с помощью вопросительного знака.Для каждого автора посчитайте суммарную стоимость книг в твердой и мягкой обложке. Используйте для этого функцию pd.pivot_table. При этом столбцы должны называться "твердая" и "мягкая", а индексами должны быть фамилии авторов. Пропущенные значения стоимостей заполните нулями, при необходимости загрузите библиотеку Numpy.
Назовите полученный датасет book_info и сохраните его в формат pickle под названием "book_info.pkl". Затем загрузите из этого файла датафрейм и назовите его book_info2. Удостоверьтесь, что датафреймы book_info и book_info2 идентичны.


In [24]:
authors_price['cover'] =  ['твердая', 'мягкая', 'мягкая', 'твердая', 'твердая', 'мягкая', 'мягкая']

In [25]:
book_info = pd.pivot_table(authors_price, 
                           values='price', 
                           index='author_name', 
                           columns='cover', 
                           aggfunc='sum',
                           fill_value=0)
# book_info.columns.name = None 
book_info

cover        мягкая  твердая
author_name                 
Островский      660        0
Тургенев        650      450
Чехов             0      950

In [26]:
import pickle

with open('book_info.pkl', 'wb') as handle:
    pickle.dump(book_info, handle, protocol=pickle.HIGHEST_PROTOCOL)

with open('book_info.pkl', 'rb') as handle:
    book_info2 = pickle.load(handle)

book_info2

cover        мягкая  твердая
author_name                 
Островский      660        0
Тургенев        650      450
Чехов             0      950

In [27]:
# 2 вариант
book_info.to_pickle('book_info.pkl')
book_info2 = pd.read_pickle('book_info.pkl')
book_info2

cover        мягкая  твердая
author_name                 
Островский      660        0
Тургенев        650      450
Чехов             0      950

In [28]:
book_info == book_info2

cover        мягкая  твердая
author_name                 
Островский     True     True
Тургенев       True     True
Чехов          True     True